### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by osoese** [sindresorhus/on-change#31]
RangeError: Maximum call stack size exceeded

I have this running for a long time and it hits this limit

**Comment by sindresorhus** [comment]
Can you include the full error message including the error stack? It would also be helpful if you could include some code that reproduces the issue.

**Comment by osoese** [comment]
C:\osoese\sapphire-alpha-0.0.1\\node_modules\on-change\index.js:87
                set(target, property, value, receiver) {
                   ^

RangeError: Maximum call stack size exceeded
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:87:6)
    at Object.set (<anonymous>)
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:93:27)
    at Object.set (<anonymous>)
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:93:27)
    at Object.set (<anonymous>)
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:93:27)
    at Object.set (<anonymous>)
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:93:27)
    at Object.set (<anonymous>)
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:93:27)
    at Object.set (<anonymous>)
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:93:27)
    at Object.set (<anonymous>)
    at Object.set (C:\osoese\sapphire-alpha-0.0.1\node_modules\on-change\index.js:93:27)
    at Object.set (<anonymous>)

**Comment by DarrenPaulWright** [comment]
Could you show us what the watched object/array looks like and what you are changing on it that produces the error?

**Comment by osoese** [comment]
its pretty complex and I did not look which part cased the error until i happens again. It updates every 2-10 seconds in some aspect of about 30 items, some of which are multiple levels. This takes hours to error, so next time I will try and follow what exactly the update was. Also I have not updated since "on-change": "^1.3.0", if that helps.

**Comment by DarrenPaulWright** [comment]
Ah, now the error stack makes more sense. There are a couple changes in 1.4.0 that I think _may_ fix your bug. Perhaps when it errors again and you figure out the change that caused the error, then update to 1.4.0 and see if it happens again?

**Comment by osoese** [comment]
update - this did not fix the issue. I think the error is just what it says it is - there is a limit to the number of changes being tracked before the call stack size is exceeded. In this program I am changing an large structure repeatedly thousands of times. I have only started to look into your code and I was unfamiliar with reflect object but I see you use it extensively. Maybe for a solution like mine a simple recall of the on-change initialization every so often (clearing the history) would work. I do not need the history in memory and if it was something I needed I could store it. I was only really interested in the actual monitoring of state for a change.

**Comment by DarrenPaulWright** [comment]
Are you using the value or previous value that are provided in the callback? As Sindre said earlier, it would be helpful if you could include some code that reproduces the issue. Even if you have a work around, I still want to figure out whats happening and find a solution. Thanks!

**Comment by DarrenPaulWright** [comment]
I'm closing this issue since we haven't heard back from you in a while. If you're still seeing this error we can re-open the issue.
