### ISSUE TITLE
Spread Operator not working for Sets ([...someSet])

### ISSUE THREAD

**Issue by dersimn** [sindresorhus/on-change#76]
```javascript
const onChange = require('on-change');

const unwatchedObject = {
    someObject: {foo: 'bar'},
    someArray: [1, 2, 3],
    someSet: new Set([1, 2, 3])
};

const watchedObject = onChange(unwatchedObject, () => {
    console.log('watchedObject changed');
});

console.log(watchedObject.someArray);
console.log([...watchedObject.someArray]);

console.log(unwatchedObject.someSet);
console.log([...unwatchedObject.someSet]);

console.log(watchedObject.someSet);
console.log([...watchedObject.someSet]);
```

Output:

```
[ 1, 2, 3 ]
[ 1, 2, 3 ]
Set(3) { 1, 2, 3 }
[ 1, 2, 3 ]
Set(3) { 1, 2, 3 }
/Users/simon/Dropbox/Coding/node/sandbox/on-change-sandbox/node_modules/on-change/index.js:135
			const result = Reflect.apply(
			                       ^

TypeError: Method Set.prototype.values called on incompatible receiver [object Object]
    at Proxy.values (<anonymous>)
    at Object.apply (/Users/simon/Dropbox/Coding/node/sandbox/on-change-sandbox/node_modules/on-change/index.js:135:27)
    at Object.<anonymous> (/Users/simon/Dropbox/Coding/node/sandbox/on-change-sandbox/spreadOperatorError.js:20:31)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by DarrenPaulWright** [comment]
Thanks for the code example! I've had many bugs reported relating to Sets and Maps, so I plan on writing tests for all their methods, but I hadn't considered spread operators.

**Comment by DarrenPaulWright** [comment]
What version are you using? I tested this in 2.2.3 and the spread operator appears to be working on Sets.

**Comment by dersimn** [comment]
You're right. The project where the bug occurred was still on `2.1.2`..🤦🏻‍♂️
