### ISSUE TITLE
Exception: This is not a Date object when details===true

### ISSUE THREAD

**Issue by lroal** [sindresorhus/on-change#99]
It throws an exception when calling a method on the date when details is true.
```
import onChange from 'on-change';

let proxy = onChange({ d: new Date() }, () => {}, { details: true});
proxy.d.getDate();
// throws
// file:///C:/Users/lars.roald/repos/rdb-demo/node_modules/on-change/index.js:229
//                         return Reflect.apply(target, thisArg, argumentsList);
//                                        ^

// TypeError: this is not a Date object.
//     at Proxy.getDate (<anonymous>)
//     at Object.apply ←[90m(file:///C:/Users/lars.roald/repos/rdb-demo/←[39mnode_modules/←[4mon-change←[24m/index.js:229:19←[90m)←[39m
//     at ←[90mfile:///C:/Users/lars.roald/repos/rdb-demo/←[39mchangeTest.mjs:4:9
```

**Comment by FPierre** [comment]
Same issue here. @lroal did you manage to find a workaround? :)

**Comment by lroal** [comment]
I think I used another tool to calculate the actual difference, [fast-json-patch](https://www.npmjs.com/package/fast-json-patch)
And just used on-change to signal a change happened.

**Comment by FPierre** [comment]
💥 wonderful idea: I actually only need to track dirty state. Way more efficient with object comparison. Thanks for the tips!
